services:
  holybot-db:
    image: postgres:18.1-alpine
    hostname: postgres
    container_name: holybot-db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --lc-collate=C --lc-ctype=C
      POSTGRES_USER: ${POSTGRES_USER:-holybot}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-holybot}
    networks:
      - holybot
    volumes:
      - holybot-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-holybot} -d ${POSTGRES_DB:-holybot}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  holybot-valkey:
    image: valkey/valkey:9.0.1-alpine
    hostname: valkey
    container_name: holybot-valkey
    restart: always
    networks:
      - holybot
    healthcheck:
      test: [ "CMD", "valkey-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

  holybot-nats:
    image: nats:2.12.3-alpine
    hostname: nats
    container_name: holybot-nats
    restart: always
    networks:
      - holybot
    volumes:
      - ./configs/nats.conf:/etc/nats/nats-server.conf
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://127.0.0.1:8222/healthz" ]
      interval: 10s
      timeout: 5s
      retries: 3

  holybot-migrator:
    build:
      context: .
      dockerfile: Shared/Dockerfile
    container_name: holybot-migrator
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_USER: ${POSTGRES_USER:-holybot}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-holybot}
    networks:
      - holybot
    depends_on:
      holybot-db:
        condition: service_healthy
    restart: "no"

  #  holybot-backend:
  #    build:
  #      context: ./Site/backend
  #      dockerfile: Dockerfile
  #    hostname: backend
  #    container_name: holybot-backend
  #    restart: always
  #    networks:
  #      - holybot
  #    depends_on:
  #      holybot-migrator:
  #        condition: service_completed_successfully
  #      holybot-db:
  #        condition: service_healthy
  #      holybot-valkey:
  #        condition: service_healthy
  #      holybot-nats:
  #        condition: service_healthy
  #      holybot-api:
  #        condition: service_healthy

  #   holybot-api:
  #     build:
  #       context: ./API
  #       dockerfile: Dockerfile
  #     networks:
  #       - holybot
  #     depends_on:
  #       holybot-migrator:
  #         condition: service_completed_successfully
  #       holybot-db:
  #         condition: service_healthy
  #       holybot-valkey:
  #         condition: service_healthy
  #       holybot-nats:
  #         condition: service_healthy

  # holybot-eventhandler:
  #   build:
  #     context: ./EventHandler
  #     dockerfile: Dockerfile
  #   networks:
  #     - holybot
  #   depends_on:
  #     holybot-migrator:
  #       condition: service_completed_successfully
  #     holybot-db:
  #       condition: service_healthy
  #     holybot-valkey:
  #       condition: service_healthy
  #     holybot-api:
  #       condition: service_healthy
  #     holybot-nats:
  #       condition: service_healthy

  # holybot-frontend:
  #   build:
  #     context: ./Site/frontend
  #     dockerfile: Dockerfile
  #   networks:
  #     - holybot
  #   depends_on:
  #     holybot-migrator:
  #       condition: service_completed_successfully
  #     holybot-db:
  #       condition: service_healthy
  #     holybot-valkey:
  #       condition: service_healthy

  # holybot-bot:
  #   build:
  #     context: ./Bot
  #     dockerfile: Dockerfile
  #   networks:
  #     - holybot
  #   depends_on:
  #     holybot-migrator:
  #       condition: service_completed_successfully
  #     holybot-db:
  #       condition: service_healthy
  #     holybot-valkey:
  #       condition: service_healthy
  #     holybot-nats:
  #       condition: service_healthy

networks:
  holybot:
    name: holybot

volumes:
  holybot-db:
    name: holybot-db
